name: ToonCraft
main: com.megacraft.tooncraft.ToonCraft
version: 0.1
author: chandlerpl
depend: [Citizens, Holograms]
authors: []

commands:
  tooncraft:
    aliases: [tc]
    usage: /<command>
permissions:
